# Generated by Django 3.1.4 on 2020-12-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0005_remove_painting_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='years',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
