# Generated by Django 3.1.4 on 2020-12-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0006_painting_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='years',
        ),
        migrations.AddField(
            model_name='painting',
            name='year',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
