# Generated by Django 3.1.4 on 2020-12-10 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0009_painting_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='year',
        ),
    ]
