# Generated by Django 3.1.4 on 2020-12-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0010_remove_painting_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
